/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "secondary": "#6b6358",
        "on-primary-fixed-variant": "#2a6038",
        "tertiary-fixed": "#f8e0a8",
        "on-tertiary-container": "#554020",
        "tertiary-container": "#c4a66a",
        "surface-container-highest": "#e4e0d8",
        "surface-tint": "#4a7c59",
        "primary-container": "#78a886",
        "outline-variant": "#c4c8bc",
        "surface": "#faf6f0",
        "inverse-on-surface": "#f5f0e8",
        "on-surface-variant": "#4a4e4a",
        "surface-dim": "#dbd7cf",
        "secondary-fixed-dim": "#d4ccbf",
        "surface-container-high": "#eae6de",
        "error-container": "#ffdad8",
        "on-surface": "#2e3230",
        "error": "#b83230",
        "primary-fixed-dim": "#8ecf9e",
        "primary": "#4a7c59",
        "tertiary": "#705c30",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0ece4",
        "on-tertiary-fixed": "#221a05",
        "tertiary-fixed-dim": "#dcc48e",
        "on-tertiary-fixed-variant": "#554020",
        "inverse-surface": "#2e3230",
        "background": "#faf6f0",
        "on-secondary": "#ffffff",
        "secondary-container": "#f0e8db",
        "primary-fixed": "#c8e8d0",
        "outline": "#74796e",
        "on-secondary-fixed-variant": "#4a4538",
        "on-primary-fixed": "#002110",
        "surface-container-low": "#f5f1ea",
        "on-primary": "#ffffff",
        "on-secondary-container": "#5e5548",
        "on-background": "#2e3230",
        "surface-variant": "#e4e0d8",
        "inverse-primary": "#8ecf9e",
        "surface-bright": "#faf6f0",
        "secondary-fixed": "#f0e8db",
        "on-primary-container": "#d8f0de",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#690005",
        "on-secondary-fixed": "#1e1a13"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Literata"],
        "display": ["Literata"],
        "body": ["Nunito Sans"],
        "label": ["Nunito Sans"]
      }
    },
  },
  plugins: [],
}
